live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x5c5c5c"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0xa6bc69"
magenta = "0xc594c5"
red = "0xe57373"
white = "0xf3f4f5"
yellow = "0xfac863"

[colors.cursor]
cursor = "0xc0c5ce"
text = "0x212121"

[colors.normal]
black = "0x212121"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0xa6bc69"
magenta = "0xc594c5"
red = "0xe57373"
white = "0xc0c5ce"
yellow = "0xfac863"

[colors.primary]
background = "0x212121"
bright_foreground = "0xf3f4f5"
foreground = "0xc0c5ce"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.3"

[font]
size = 13

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 2500
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5
