#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.


# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-width 1

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
#riverctl float-filter-add app-id float
#riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
#riverctl csd-filter-add app-id "gedit"

riverctl focus-follows-cursor normal

riverctl attach-mode bottom

riverctl input pointer-1267-5-Elan_Touchpad tap enabled
riverctl input pointer-1267-5-Elan_Touchpad disable-while-typing disabled
riverctl input pointer-1267-5-Elan_Touchpad natural-scroll enabled
riverctl input pointer-1267-5-Elan_Touchpad drag enabled

source ~/.config/river/keybindings
source ~/.config/river/luatile

riverctl keyboard-layout gb

if [[ -f ~/.config/river/local ]]; then
    source ~/.config/river/local
fi

riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "systemctl --user start plasma-polkit-agent"
riverctl spawn waybar
riverctl spawn kanshi
#riverctl spawn "rivertile -view-padding 6 -outer-padding 6"
#riverctl spawn "stacktile --per-tag-config --inner-padding 5 --outer-padding 5"
riverctl spawn dunst
