#! /bin/sh
sxhkd &
#feh --bg-scale ~/Pictures/wallpaper &
/home/josh/.fehbg &
xsetroot -cursor_name left_ptr &
picom &
dunst &
#dropbox &
#mpd &
#[[ -z $(pgrep -xU $UID mpdscribble) ]] && mpdscribble &
/home/josh/.config/polybar/launch.sh &

#bspc monitor DP-2 -d I II III IV V
#bspc monitor DVI-D-1 -d VI VII VIII IX X

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          10

bspc config borderless_monocle         true
bspc config single_monocle             true

bspc config split_ratio          0.50

bspc config normal_border_color '#212121'
bspc config active_border_color '#d64e4e'
bspc config focused_border_color '#505050'
bspc config presel_feedback_color '#323232'

bspc rule -a Pavucontrol state=floating
