#!/bin/sh

dir="/sys/class/power_supply/"

b0="$(cat $dir/BAT0/capacity)"
#b1="$(cat $dir/BAT1/capacity)"

combined="$(( (b0) / 1 ))"

state="$(cat $dir/BAT0/status)"

[ "$state" = Charging ] && i='' ||
	case "$((combined / 20))" in
		# 0-19
		0) i='';;
		# 20-39
		1) i='';;
		# 40-59
		2) i='';;
		# 60-79
		3) i='';;
		# everything else, assume full (80-100)
		*) i='';;
	esac

echo "$i $combined%"
